# permissions for end users to view people.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: person-viewer-role
rules:
- apiGroups:
  - sample.siming.io
  resources:
  - people
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sample.siming.io
  resources:
  - people/status
  verbs:
  - get
