---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - sample.siming.io
  resources:
  - people
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sample.siming.io
  resources:
  - people/finalizers
  verbs:
  - update
- apiGroups:
  - sample.siming.io
  resources:
  - people/status
  verbs:
  - get
  - patch
  - update
